#ifndef __CERTS_H_
#define __CERTS_H_

#include <Arduino.h>

const char ca_pem[] = R"(-----BEGIN CERTIFICATE-----
MIICCzCCAbGgAwIBAgIUMy5/d7HxUzdCvvYm9ezN9VumPUgwCgYIKoZIzj0EAwIw
WzELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoMGElu
dGVybmV0IFdpZGdpdHMgUHR5IEx0ZDEUMBIGA1UEAwwLYWJjc29sdXRpb24wHhcN
MjUwNzIyMDkyOTM0WhcNMjYwNzIyMDkyOTM0WjBbMQswCQYDVQQGEwJBVTETMBEG
A1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkg
THRkMRQwEgYDVQQDDAthYmNzb2x1dGlvbjBZMBMGByqGSM49AgEGCCqGSM49AwEH
A0IABFFkg8kjDPhPeAN8fonJlSjiJn5nUgyGMp/PScSy676xCOA7ho1oPntQlvLv
fhcBa/ZBUseMMVBB21Iu9iZIEPqjUzBRMB0GA1UdDgQWBBSESsuQe8JeHce+G+VJ
WYWWSP3u+DAfBgNVHSMEGDAWgBSESsuQe8JeHce+G+VJWYWWSP3u+DAPBgNVHRMB
Af8EBTADAQH/MAoGCCqGSM49BAMCA0gAMEUCIDGTpl4BO0jnrR3TzIjpb1t91NuZ
l3ViqyAp8f+s4LsUAiEA981z3tD5fDNwPHGtrUBxUuZOG53zRmz1XdHb9WxdSoE=
-----END CERTIFICATE-----
)";

const char key_pem[] = R"(-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIPzTp3A7tqnGpR5NirHxdnNpKxqqsUrRFBeimi5q8ZINoAoGCCqGSM49
AwEHoUQDQgAEhOa3EfWQ6pwp6k9u6fF/kXntWps9DOT+rOuOry+LHMtGvfmHr9PU
hEHE2DRs/sv/KGcO03aGFag/KuoH4rqB+g==
-----END EC PRIVATE KEY-----
)";

const char cert_pem[] = R"(-----BEGIN CERTIFICATE-----
MIIB3zCCAYWgAwIBAgIUUw3P6/BG4cHNUSM4EmV4tvQftQowCgYIKoZIzj0EAwIw
RTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoMGElu
dGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yNTA3MjMwOTUwMjRaFw0yNjA3MjMw
OTUwMjRaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYD
VQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwWTATBgcqhkjOPQIBBggqhkjO
PQMBBwNCAASE5rcR9ZDqnCnqT27p8X+Ree1amz0M5P6s646vL4scy0a9+Yev09SE
QcTYNGz+y/8oZw7TdoYVqD8q6gfiuoH6o1MwUTAdBgNVHQ4EFgQUpxADTT6Gq4oX
7iXNDNC0/7jDufswHwYDVR0jBBgwFoAUpxADTT6Gq4oX7iXNDNC0/7jDufswDwYD
VR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNIADBFAiA+DQr1uABIdAHZVTw6kyk5
dG5f1pp9PdgUyCoUbtK7ZQIhAIQXjabYcLJaE2LOm6hXQhdumdINfqeqrhD2p+e7
WCSz
-----END CERTIFICATE-----
)";

#endif